apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: 8000
      protocol: TCP
  selector:
    app: api
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
