apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
    app: db
    {{- include "todo-app.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.config.POSTGRES_DB }}
  POSTGRES_USER: {{ .Values.config.POSTGRES_USER }}
