apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-app.fullname" . }}--db-config
  labels:
    app: {{ include "todo-app.fullname" . }}--db
    {{- include "todo-app.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.config.POSTGRES_DB }}
  POSTGRES_USER: {{ .Values.config.POSTGRES_USER }}
