apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "todo-app.fullname" . }}--db-pvc
  labels:
    app: {{ include "todo-app.fullname" . }}--db
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.space }}