apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    app: db
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: {{ .Values.storage.space }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: {{ .Values.storage.mountPath }}