apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "todo-app.fullname" . }}--my-selfsigned-ca
  namespace: {{ include "todo-app.fullname" . }}--cert
spec:
  isCA: true
  commonName: {{ include "todo-app.fullname" . }}--my-selfsigned-ca
  secretName: {{ include "todo-app.fullname" . }}--root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ include "todo-app.fullname" . }}--selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
