apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ include "todo-app.fullname" . }}--my-ca-cluster-issuer
spec:
  ca:
    secretName: {{ include "todo-app.fullname" . }}--root-secret
