apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "todo-app.fullname" . }}--my-ca-issuer
  namespace: {{ include "todo-app.fullname" . }}--cert
spec:
  ca:
    secretName: {{ include "todo-app.fullname" . }}--root-secret
