apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: db-manager-role-binding
subjects:
  - kind: User
    name: db-manager
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: db-manager-role
  apiGroup: rbac.authorization.k8s.io
