apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developer-role
rules:
  - apiGroups: [""]
    resources:
      ["pods", "services", "endpoints", "persistentvolumeclaims", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
