apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-keeper-role-binding
  namespace: default
subjects:
  - kind: User
    name: secret-keeper
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: secret-keeper-role
  apiGroup: rbac.authorization.k8s.io
