version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=$POSTGRES_NAME
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    networks:
      - be-db
    ports:
      - 5432:5432
  backend:
    image: backend:v1
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=$POSTGRES_NAME
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    networks:
      - be-fe
      - be-db
    depends_on:
      - db
  frontend:
    image: frontend:v2
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:80
    networks:
      - be-fe
    depends_on:
      - backend

networks:
  be-fe:
    driver: bridge
  be-db:
    driver: bridge
volumes:
  db-data:
    driver: local
