version: '3.8'

services:
  backend:
    image: backend:v1
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
  frontend:
    image: frontend:v2
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 3001:80
