apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  # type: ClusterIP
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      nodePort: 30004
      targetPort: 8000
  selector:
    app: api
