apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
    app: db
data:
  POSTGRES_DB: postgres
  POSTGRES_NAME: postgres
  POSTGRES_USER: postgres
  POSTGRES_HOST: localhost
  POSTGRES_PORT: "5432"
