apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    app: db
    type: local
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/db/data"
