apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  type: NodePort
  # type: LoadBalancer
  ports:
    - protocol: TCP
      nodePort: 30002
      port: 5050
      targetPort: 5050
  selector:
    app: ui
