apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui-container
          image: dmitrylv/todo-fe:latest
          ports:
            - containerPort: 5050
          # env:
          #   - name: API_SERVICE_SERVICE_HOST
          #     value: $API_SERVICE_SERVICE_HOST
          #   - name: API_SERVICE_SERVICE_PORT
          #     value: $API_SERVICE_SERVICE_PORT
