apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ui
      version: v1
  template:
    metadata:
      labels:
        app: ui
        version: v1
    spec:
      containers:
        - name: ui-container
          image: dmitrylv/todo-fe:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5050
