apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-app.fullname" . }}--db-deployment
  labels:
    app: {{ include "todo-app.fullname" . }}--db
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.deployment.db.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "todo-app.fullname" . }}--db
      {{- include "todo-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "todo-app.fullname" . }}--db
        {{- include "todo-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "todo-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "todo-app.fullname" . }}--db-container
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.deployment.db.image.repository }}:{{ .Values.deployment.db.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.deployment.db.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.db.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "todo-app.fullname" . }}--db-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "todo-app.fullname" . }}--db-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "todo-app.fullname" . }}--db-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: {{ include "todo-app.fullname" . }}--db-vol
      volumes:
        - name: {{ include "todo-app.fullname" . }}--db-vol
          persistentVolumeClaim:
            claimName: {{ include "todo-app.fullname" . }}--db-pvc
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
