apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}--ui
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.ui.type }}
  ports:
    - port: {{ .Values.service.ui.port }}
      targetPort: 5050
      protocol: TCP
  selector:
    app: {{ include "todo-app.fullname" . }}--ui
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
