apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "todo-app.fullname" . }}--api-allow-db-and-ui-request
spec:
  podSelector:
    matchLabels:
      app: {{ include "todo-app.fullname" . }}--api
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: {{ include "todo-app.fullname" . }}--db
      ports:
        - protocol: TCP
          port: {{ .Values.service.db.port }}
    - from:
        - podSelector:
            matchLabels:
              app: {{ include "todo-app.fullname" . }}--ui
      ports:
        - protocol: TCP
          port: {{ .Values.service.ui.port }}
