apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "todo-app.fullname" . }}--developer-role-binding
  namespace: default
subjects:
  - kind: User
    name: {{ include "todo-app.fullname" . }}--developer
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: {{ include "todo-app.fullname" . }}--developer-role
  apiGroup: rbac.authorization.k8s.io
