apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "todo-app.fullname" . }}--secret-keeper-role
rules:
  - apiGroups: [""]
    resources: ["secret"]
    verbs: ["get", "list", "watch"]
